/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

namespace APIGateway.Thrift.Generated.KafkaTypes
{

  public partial class KafkaInsertRequest : TBase
  {
    private global::APIGateway.Thrift.Generated.BaseTypes.QueueMessage _insertQueueMessage;

    public global::APIGateway.Thrift.Generated.BaseTypes.QueueMessage InsertQueueMessage
    {
      get
      {
        return _insertQueueMessage;
      }
      set
      {
        __isset.insertQueueMessage = true;
        this._insertQueueMessage = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool insertQueueMessage;
    }

    public KafkaInsertRequest()
    {
    }

    public KafkaInsertRequest DeepCopy()
    {
      var tmp0 = new KafkaInsertRequest();
      if((InsertQueueMessage != null) && __isset.insertQueueMessage)
      {
        tmp0.InsertQueueMessage = (global::APIGateway.Thrift.Generated.BaseTypes.QueueMessage)this.InsertQueueMessage.DeepCopy();
      }
      tmp0.__isset.insertQueueMessage = this.__isset.insertQueueMessage;
      return tmp0;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                InsertQueueMessage = new global::APIGateway.Thrift.Generated.BaseTypes.QueueMessage();
                await InsertQueueMessage.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("KafkaInsertRequest");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if((InsertQueueMessage != null) && __isset.insertQueueMessage)
        {
          field.Name = "insertQueueMessage";
          field.Type = TType.Struct;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await InsertQueueMessage.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is KafkaInsertRequest other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.insertQueueMessage == other.__isset.insertQueueMessage) && ((!__isset.insertQueueMessage) || (System.Object.Equals(InsertQueueMessage, other.InsertQueueMessage))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((InsertQueueMessage != null) && __isset.insertQueueMessage)
        {
          hashcode = (hashcode * 397) + InsertQueueMessage.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("KafkaInsertRequest(");
      int tmp1 = 0;
      if((InsertQueueMessage != null) && __isset.insertQueueMessage)
      {
        if(0 < tmp1++) { sb.Append(", "); }
        sb.Append("InsertQueueMessage: ");
        InsertQueueMessage.ToString(sb);
      }
      sb.Append(')');
      return sb.ToString();
    }
  }

}
