/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

namespace BOA.APIGateway.Thrift.Generated.BaseTypes
{
  public enum ApplicationSide
  {
    client = 0,
    server = 1,
    database = 2,
    databaseConnection = 3,
    transportation = 4,
    dispatcher = 5,
    pipeline = 6,
    broadcastTransportation = 7,
    orchestration = 8,
    accountingEngine = 9,
    commissionEngine = 10,
    slipEngine = 11,
    tellerEngine = 12,
    authorizationEngine = 13,
    futureTransactionEngine = 14,
    revokeEngine = 15,
    workflowEngine = 16,
    accountControl = 17,
    reverseAccountControl = 18,
    ruleEngine = 19,
    fraudEngine = 20,
    transactionAuthorization = 21,
  }
}
