/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

namespace APIGateway.Thrift.Generated.BaseTypes
{

  public partial class ResponseBase : TBase
  {
    private List<global::APIGateway.Thrift.Generated.BaseTypes.Result> _results;
    private global::APIGateway.Thrift.Generated.BaseTypes.Severity _maxSeverityLevel;
    private bool _success;
    private string _businessKey;

    public List<global::APIGateway.Thrift.Generated.BaseTypes.Result> Results
    {
      get
      {
        return _results;
      }
      set
      {
        __isset.results = true;
        this._results = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="global::APIGateway.Thrift.Generated.BaseTypes.Severity"/>
    /// </summary>
    public global::APIGateway.Thrift.Generated.BaseTypes.Severity MaxSeverityLevel
    {
      get
      {
        return _maxSeverityLevel;
      }
      set
      {
        __isset.maxSeverityLevel = true;
        this._maxSeverityLevel = value;
      }
    }

    public bool Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }

    public string BusinessKey
    {
      get
      {
        return _businessKey;
      }
      set
      {
        __isset.businessKey = true;
        this._businessKey = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool results;
      public bool maxSeverityLevel;
      public bool success;
      public bool businessKey;
    }

    public ResponseBase()
    {
      this._maxSeverityLevel = global::APIGateway.Thrift.Generated.BaseTypes.Severity.Information;
      this.__isset.maxSeverityLevel = true;
    }

    public ResponseBase DeepCopy()
    {
      var tmp6 = new ResponseBase();
      if((Results != null) && __isset.results)
      {
        tmp6.Results = this.Results.DeepCopy();
      }
      tmp6.__isset.results = this.__isset.results;
      if(__isset.maxSeverityLevel)
      {
        tmp6.MaxSeverityLevel = this.MaxSeverityLevel;
      }
      tmp6.__isset.maxSeverityLevel = this.__isset.maxSeverityLevel;
      if(__isset.success)
      {
        tmp6.Success = this.Success;
      }
      tmp6.__isset.success = this.__isset.success;
      if((BusinessKey != null) && __isset.businessKey)
      {
        tmp6.BusinessKey = this.BusinessKey;
      }
      tmp6.__isset.businessKey = this.__isset.businessKey;
      return tmp6;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  TList _list7 = await iprot.ReadListBeginAsync(cancellationToken);
                  Results = new List<global::APIGateway.Thrift.Generated.BaseTypes.Result>(_list7.Count);
                  for(int _i8 = 0; _i8 < _list7.Count; ++_i8)
                  {
                    global::APIGateway.Thrift.Generated.BaseTypes.Result _elem9;
                    _elem9 = new global::APIGateway.Thrift.Generated.BaseTypes.Result();
                    await _elem9.ReadAsync(iprot, cancellationToken);
                    Results.Add(_elem9);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                MaxSeverityLevel = (global::APIGateway.Thrift.Generated.BaseTypes.Severity)await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Bool)
              {
                Success = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.String)
              {
                BusinessKey = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("ResponseBase");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if((Results != null) && __isset.results)
        {
          field.Name = "results";
          field.Type = TType.List;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          {
            await oprot.WriteListBeginAsync(new TList(TType.Struct, Results.Count), cancellationToken);
            foreach (global::APIGateway.Thrift.Generated.BaseTypes.Result _iter10 in Results)
            {
              await _iter10.WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteListEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.maxSeverityLevel)
        {
          field.Name = "maxSeverityLevel";
          field.Type = TType.I32;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI32Async((int)MaxSeverityLevel, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.success)
        {
          field.Name = "success";
          field.Type = TType.Bool;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteBoolAsync(Success, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((BusinessKey != null) && __isset.businessKey)
        {
          field.Name = "businessKey";
          field.Type = TType.String;
          field.ID = 4;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(BusinessKey, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is ResponseBase other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.results == other.__isset.results) && ((!__isset.results) || (TCollections.Equals(Results, other.Results))))
        && ((__isset.maxSeverityLevel == other.__isset.maxSeverityLevel) && ((!__isset.maxSeverityLevel) || (System.Object.Equals(MaxSeverityLevel, other.MaxSeverityLevel))))
        && ((__isset.success == other.__isset.success) && ((!__isset.success) || (System.Object.Equals(Success, other.Success))))
        && ((__isset.businessKey == other.__isset.businessKey) && ((!__isset.businessKey) || (System.Object.Equals(BusinessKey, other.BusinessKey))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Results != null) && __isset.results)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Results);
        }
        if(__isset.maxSeverityLevel)
        {
          hashcode = (hashcode * 397) + MaxSeverityLevel.GetHashCode();
        }
        if(__isset.success)
        {
          hashcode = (hashcode * 397) + Success.GetHashCode();
        }
        if((BusinessKey != null) && __isset.businessKey)
        {
          hashcode = (hashcode * 397) + BusinessKey.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("ResponseBase(");
      int tmp11 = 0;
      if((Results != null) && __isset.results)
      {
        if(0 < tmp11++) { sb.Append(", "); }
        sb.Append("Results: ");
        Results.ToString(sb);
      }
      if(__isset.maxSeverityLevel)
      {
        if(0 < tmp11++) { sb.Append(", "); }
        sb.Append("MaxSeverityLevel: ");
        MaxSeverityLevel.ToString(sb);
      }
      if(__isset.success)
      {
        if(0 < tmp11++) { sb.Append(", "); }
        sb.Append("Success: ");
        Success.ToString(sb);
      }
      if((BusinessKey != null) && __isset.businessKey)
      {
        if(0 < tmp11++) { sb.Append(", "); }
        sb.Append("BusinessKey: ");
        BusinessKey.ToString(sb);
      }
      sb.Append(')');
      return sb.ToString();
    }
  }

}
