/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

namespace APIGateway.Thrift.Generated.BaseTypes
{
  public enum Severity
  {
    Error = 0,
    Warning = 1,
    Information = 2,
    BusinessError = 3,
    LowerError = 4,
  }
}
